Repository cachix/git-hooks.nix, pull requests merged in 2024-07, with the labels that each got.

#469 docs: clarify terraform-format
  README.md
Labels: documentation

#471 feat: add cabal-gild
  flake.lock
  flake.nix
  modules/hooks.nix
  nix/call-tools.nix
  nix/tools.nix
Labels: new-hook

#468 Fix typstyle argument
  modules/hooks.nix
Labels: bug
