Repository cachix/git-hooks.nix, pull requests merged in 2024-10, with the labels that each got.

#503 feat(statix): add settings
  modules/hooks.nix
Labels: enhancement

#510 statix: skip adding `--ignore` if empty
  modules/hooks.nix
Labels: bug

#516 fix(rustfmt): add cargoManifestPath back
  modules/hooks.nix
Labels: bug

#501 add golines pre-commit hook
  modules/hooks.nix
  nix/tools.nix
Labels: enhancement

#521 Spelling: Check *.org files by default
  modules/hooks.nix
Labels: enhancement

#522 fix: avoid use of deprecated stage names
  README.md
  modules/hooks.nix
  nix/installation-test.nix
  nix/run.nix
Labels: tech-debt
