Repository cachix/git-hooks.nix, pull requests merged in 2025-03, with the labels that each got.

#553 yamlfmt: allow formatting during hook run
  modules/hooks.nix
Labels: enhancement

#557 feat: openapi spec validator
  README.md
  modules/hooks.nix
  nix/tools.nix
Labels: new-hook

#555 feat: add proselint
  modules/hooks.nix
  nix/tools.nix
Labels: new-hook

#563 Add a `configPath` option
  modules/pre-commit.nix
Labels: enhancement

#559 fix(fourmolu): refer to its own settings
  modules/hooks.nix
Labels: bug

#568 docs: sort sections by name
  README.md
Labels: documentation
